name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.x
          - 14.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # libgbm-dev is required by Puppeteer 3+
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev ghostscript poppler-utils
      if: ${{ runner.os == 'Linux' }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Lint and test
      run: |
        npm run lint
        npm t
    - name: Build binary
      run: |
        npm run build linux
    - name: Smoke test
      run: |
        unzip asciidoctor-web-pdf-linux.zip -d out
        ./out/asciidoctor-web-pdf ./out/examples/document/basic-example.adoc -o basic.pdf
      working-directory: build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          npm ci
      - name: Build binary
        run: |
          npm run build mac
      - name: Smoke test
        run: |
          unzip asciidoctor-web-pdf-mac.zip -d out
          ./out/asciidoctor-web-pdf ./out/examples/document/basic-example.adoc -o basic.pdf
        working-directory: build
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          npm ci
      - name: Build binary
        run: |
          npm run build win
      - name: Smoke test
        run: |
          unzip asciidoctor-web-pdf-win.zip -d out
          out\asciidoctor-web-pdf.exe out\examples\document\basic-example.adoc -o basic.pdf
        shell: cmd
        working-directory: build
